### ISSUE TITLE
nomad_job resource information when planning

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/terraform-provider-nomad#247]
Hi, 

I was wondering if it's possible to modify the nomad_job resource to output/include more information when doing a terraform plan. Currently we can see the changes on the job but it would be usefull to receive some information like nomad plan does:

Exmaple of output for nomad plan
```
+/- Job: "test"
+/- Task Group: "test-group" (1 canary, 1 ignore)
  +/- Task: "task-a" (forces create/destroy update)
 ....
  +/- Task Group: "task-b" (1 in-place update)
 ....
```
This information about what's about to happen it's really usefull for us.

Thanks in advance.

**Comment by lgfa29** [comment]
Hi @jorgemarey 👋 

Unfortunately this would not be possible until, at least, #1 is fixed. The Terraform and Nomad state are two different things and controlled differently by each tool. 

A fix for #1 would allow better diffs because then each jobspec field would be tracked by Terraform as well, but until then, there's nothing we can do to improve it....

I will close this and we re-evaluate the diff quality for jobs when #1 is fixed.
