### ISSUE TITLE
file resource for nomad volume

### ISSUE THREAD

**Issue by thatsk** [hashicorp/terraform-provider-nomad#283]
resource "nomad_volume" "mysql_volume" {
  jobspec = file("${path.module}/volume.hcl")
}

is there way we can pass like this rather then defining into it.

**Comment by lgfa29** [comment]
Thanks for the idea @thatsk 🙂 

Unfortunately this approach goes against the way Terraform works, and it has given a lot of headache in the `nomad_job` resource. Since all you're give to Terraform is a string, it can't actually compare its own local state and the remote state in Nomad to detect changes, which results in problems like #1 and prevents us from exposing values in the resource like in https://github.com/hashicorp/terraform-provider-nomad/issues/125#issuecomment-674251130.

While I can see how it would be great to be able to use the same input in the `nomad` and `terraform` CLI the experience we had shows that it actually results in more problems than it's worth 😕
