### ISSUE TITLE
Cannot update from system job to service

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/terraform-provider-nomad#365]
Sorry to be the bearer of bugs :( 
When I change my job spec from type `system` to `service` terraform complains that it cannot update `system` job to `service` job.

**Comment by lgfa29** [comment]
Hi @blmhemu 👋 

That's actually the expected result, Nomad does not allow to change job types. And given #1 we're not able to determine individual attribute changes from the Terraform side the error can only be detected on apply.

I'm going to close this, since this is the expected outcome, but let me know if you have any more questions.
