### ISSUE TITLE
Ctrl + C interrupt ignored when waiting for volume deletion.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/terraform-provider-nomad#367]
Consider the following case.
1. Setup CSI plugin.
2. In terraform, create Volumes.
3. Delete CSI controller / node => Plugin is unhealthy.
4. In terraform, remove the volume resource (from step 2)
5. Now terraform could not delete volume due to unavailable plugin and waits for it. 

Now you realize that the csi plugin is not active and try to interrupt terraform apply - it does not work, the retry still continues (till the time limit is reached ~ 5 min).

**Comment by lgfa29** [comment]
Hi @blmhemu 👋 

I was going to comment saying that this is an expected Terraform behaviour since it doesn't know when it is safe to interrupt an apply, but it seems like this is [no longer true](https://github.com/hashicorp/terraform-plugin-sdk/issues/73) on v2 of the SDK and using the context version of the CRUD methods and `RetryContext` may be able to handle this.

This change is a bit more that I would like to have on `nomad_volume` and `nomad_external_volume` so I'm considering undoing the use of retry there to avoid any potential bugs and only implement this on the new `nomad_csi_volume` and `nomad_csi_volume_registration`.

**Comment by lgfa29** [comment]
The fix was shipped in v2.0.0-rc.2, if you have a chance, give it a try and let us know if the problem still happens 🙂
