### ISSUE TITLE
Unrecognized role field with vault integration in nomad 1.7 

### ISSUE THREAD

**Issue by fmp88** [hashicorp/terraform-provider-nomad#400]
Hi there,

I setup a Nomad 1.7.1 cluster with vault integration enabled. 
Submitting the example job from the documentation works fine
https://developer.hashicorp.com/nomad/docs/integrations/vault-integration

But when I try to deploy a job through the terraform nomad provider it fails.
The job parser does not recognize the new field "role" inside the vault block. 

### Terraform Version
Terraform v1.6.5
on linux_amd64

This command will also output the provider version, please include that as well.

source = "hashicorp/nomad"
version = "2.0.0"

### Nomad Version
Run `nomad server members` in your target node to view which version of Nomad is running. Make sure to include the entire version output.

### Provider Configuration
I use the default/implicit configuration

### Affected Resource(s)
- nomad_job

### Expected Behavior
The nomad provider should be able to recognize the new field "role" in the job and deploy the job

### Actual Behavior
The job does not start, and fails with a message that the field "role" is not recognized

**Comment by lgfa29** [comment]
Hi @fmp88 👋 

Thanks for the report, you were probably the first to try it on Nomad 1.7 😄 

Every new version of Nomad that adds new jobspec fields require an update on the Nomad SDK, which was done in #404. A new version of the provider should be available soon, and that will include support for the new attributes.

Since we have already updated the Nomad dependency I'm going to close this one.

Feel free to open new issues if you find any other problems!

**Comment by fmp88** [comment]
Hi @lgfa29 
thats great news, can you estimate when this new version of the provider will be released?

Thanks

**Comment by lgfa29** [comment]
It's just been released 🙂 

It can take a few hours for the Terraform registry to update, but it should be available soon.
