### ISSUE TITLE
[Feature Request] Add JWT type to nomad_acl_auth_method

### ISSUE THREAD

**Issue by flexwie** [hashicorp/terraform-provider-nomad#422]
The `nomad_acl_auth_method` resource currently only has support for OIDC type methods. It would be great, if the JWT type would also be supported (along with the added parameters in the config block).

**Comment by lgfa29** [comment]
Thanks for the suggestion @flexwie!

It does seem like the `nomad_acl_auth_method` is a little outdated, so it would be really nice to update it.

**Comment by flexwie** [comment]
I have no experience writing Terraform resources, but I can give this a shot!

**Comment by lgfa29** [comment]
That's awesome @flexwie!

Resources in Terraform providers have a very simple CRUD (Create, Retrieve, Update, and Delete) interface. Since a resource already exists, you mostly need to update its configuration and populate the values so they're stored in the Terraform state.

I believe you will need to add the new fields here:
https://github.com/hashicorp/terraform-provider-nomad/blob/ca904527503205ef662a596cd90b70aa44d4f2ce/nomad/resource_acl_auth_method.go#L79-L142

And then update these two functions that are used to map values from the internal Terraform representation to the Nomad SDK (and vice-versa):
https://github.com/hashicorp/terraform-provider-nomad/blob/ca904527503205ef662a596cd90b70aa44d4f2ce/nomad/resource_acl_auth_method.go#L287-L369

Lastly the new values should be documented in https://github.com/hashicorp/terraform-provider-nomad/blob/main/website/docs/r/acl_auth_method.html.markdown. You can use https://registry.terraform.io/tools/doc-preview to preview changes there.

Let me know if you have any questions!
