### ISSUE TITLE
nomad_acl_auth_method thinks "token_name_format" is changed even if it hasn't

### ISSUE THREAD

**Issue by msherman13** [hashicorp/terraform-provider-nomad#456]
### Terraform Version
1.8.3

### Nomad Version
1.6.2

### Nomad PROVIDER Version
2.2.0

### Provider Configuration
```hcl
provider "nomad" {
  address     = redacted
  skip_verify = true
}
```

### Affected Resource(s)
- nomad_acl_auth_method

### Expected Behavior
Resource does not update in place on every run

### Actual Behavior
Resource updates in place on every run, indicating the below:

```
  # module.redacted.nomad_acl_auth_method.redacted will be updated in-place
  ~ resource "nomad_acl_auth_method" "redacted" {
        id                = "redacted"
        name              = "redacted"
      + token_name_format = "${auth_method_type}-${auth_method_name}"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This resource is being used to add an oidc authentication method. Everything works as expected but the resource always thinks the token_name_format is changed (I don't specify token_name_format at all in the resource). If i try to set token_name_resource like below, the issue still occurs.
```
token_name_format = "$${auth_method_type}-$${auth_method_name}"
```

**Comment by jrasell** [comment]
Hi @msherman13 and thanks for raising this issue.

The token name format feature was added as part of [Nomad v.1.7.0](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#170-december-07-2023) and therefore is not available within the version 1.6.2 which you are running. This manifests in the Terraform provider in the way you're seeing as the unmarshalling of the return object will always show the field as empty, as it doesn't exist in the return object.

I used the following HCL within a `main.tf` file to ensure this bug does not exist on latest versions of Nomad or the Terraform provider:

```hcl
provider "nomad" {
  address   = "http://localhost:4646"
  secret_id = "SOMEID"
}

resource "nomad_acl_auth_method" "my_nomad_acl_auth_method" {
  name              = "my-nomad-acl-auth-method"
  type              = "OIDC"
  token_locality    = "global"
  max_token_ttl     = "10m0s"
  token_name_format = "$${auth_method_type}-$${value.user}"
  default           = true

  config {
    oidc_discovery_url    = "https://uk.auth0.com/"
    oidc_client_id        = "someclientid"
    oidc_client_secret    = "someclientsecret-t"
    bound_audiences       = ["someclientid"]
    allowed_redirect_uris = [
      "http://localhost:4649/oidc/callback",
      "http://localhost:4646/ui/settings/tokens",
    ]
    list_claim_mappings = {
      "http://nomad.internal/roles" : "roles"
    }
  }
}
``` 

In order to use the token name format feature, you will need to upgrade your installed Nomad version. Thanks.
